default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: llc
  password: 123456
  host: localhost
  port: 5001

development:
  <<: *default
  database: shop_rails_1_development

test:
  <<: *default
  database: shop_rails_1_test

production:
  <<: *default
  database: shop_rails_1_production
  username: shop_rails_1
  password: <%= ENV['SHOP_RAILS_1_DATABASE_PASSWORD'] %>
