default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: harrisking 
  password: 123456
  host: 192.168.99.100 
  port: 5001 


development:
  <<: *default
  database: shop_rails_1_development
  
test:
  <<: *default
  database: shop_rails_1_test

production:
  <<: *default
  database: shop_rails_1_production
  password: <%= ENV['SHOP_RAILS_1_DATABASE_PASSWORD'] %>
